version: '2'
services:
  config-server:
    image: icommerce/icommerce-config-server
    container_name: config-server
    mem_limit: 512M
    ports:
      - 8888:8888

  order-service:
    image: icommerce/icommerce-order-service
    container_name: icommerce-oder-service
    mem_limit: 512M
    depends_on:
      - config-server
    entrypoint: ["./dockerize","-wait=tcp://config-server:8888","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
      - 8081:8081

  user-service:
    image: icommerce/icommerce-user-service
    container_name: icommerce-user-service
    mem_limit: 512M
    depends_on:
      - config-server
    entrypoint: ["./dockerize","-wait=tcp://config-server:8888","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
      - 8082:8082

  api-gateway:
    image: icommerce/icommerce-api-gateway
    container_name: icommerce-api-gateway
    mem_limit: 512M
    depends_on:
      - config-server
    entrypoint: ["./dockerize","-wait=tcp://config-server:8888","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
        - 8083:8083
