version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "order:5:1"
#  apache:
#    build: docker/apache
#    links:
#      - api-gateway
#      - order-service
#      - config-server
#      - user-service
#    ports:
#      - "8080:80"
  postgres:
    build: docker/postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: admin
    ports:
        - "5432:5432"
#  mysql-db:
#    build: docker/postgres
#    ports:
#        - "3307:3306"
#    environment:
#       MYSQL_ROOT_PASSWORD: 123456
#       MYSQL_USER: dbuser
#       MYSQL_PASSWORD: dbpass
  api-gateway:
    build: icommerce-api-gateway
    links:
      - kafka
      - postgres
    ports:
      - 8081:8080
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  order-service:
    build: icommerce-order-service
    container_name: order-service
    links:
      - kafka
      - postgres
    ports:
      - 8082:8080
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  customer-service:
    build: icommerce-customer-service
    container_name: customer-service
    links:
      - kafka
      - postgres
    ports:
      - 8083:8080
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
