version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "order:5:1"
#  apache:
#    build: docker/apache
#    links:
#      - api-gateway
#      - order-service
#      - config-server
#      - user-service
#    ports:
#      - "8080:80"
  postgres:
    build: docker/postgres
    environment:
      POSTGRES_PASSWORD: dbpass
      POSTGRES_USER: dbuser
    ports:
        - "5432:5432"
  api-gateway:
    build: icommerce-api-gateway
    links:
      - kafka
      - postgres
    ports:
      - 8081:8080
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  order-service:
    build: icommerce-api-gateway
    links:
      - kafka
      - postgres
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  config-server:
    build: icommerce-api-gateway
    links:
      - kafka
      - postgres
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  user-service:
    build: icommerce-api-gateway
    links:
      - kafka
      - postgres
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
